### ISSUE TITLE
Add pass_thru support

### ISSUE THREAD

**Issue by christoph-kluge** [lindenlab/caddy-s3-proxy#27]
I'm playing around with this tiny awesome module. 
My use-case: I would like to use the s3proxy module as a full-page-cache so I wold like to pass the request down the road if s3 returns a 404. 

Was this deleted on purpose?

It's still documented here: https://caddyserver.com/docs/modules/http.handlers.s3proxy#pass_thru
Got deleted in this PR: https://github.com/lindenlab/caddy-s3-proxy/pull/3/files#diff-05eba8ab715ef36a460f8203a4d9dc5215b78d3ca47e1acb2fe25a8ed61f6274L58

**Comment by rayjlinden** [comment]
Actually, I had the directive in there but never got around to implementing
in the backend.  I then deleted the directive so that everything published
was working.

(Then I found out the caddy website has a bug and those descriptions never
update!!!)

In any case, I am open to supporting this feature in some way.  Please add
it as an issue and describe what is needed from your perspective.

Of course, I would also welcome a pull-request that implements the changes
needed.
I can commit to getting the feature done at some point (I agree it would be
useful) - but not a strong timeline (I have a lot going on at work at the
moment.) - but if you do submit a PR I can probably get it done much
faster...

Ray

**Comment by christoph-kluge** [comment]
Hey Ray, thanks for this detailed answer. I've recently contributed a simple changed to the caddyserver but I'm not an golang expert at all. Touched golang for the first time to be honest.

In my case I would much appreciate the following acceptance criterias

* Support `pass_thru` option as soon as S3 returns with a status code > 400
* Support custom s3 key based on request parameters (e.g. use host as prefix, transform query params to sha1, use sha1 for the whole request uri)

In my test scenario I'm using the following Caddyfile.

```
{
    admin off
    http_port 80
    https_port 443
    cert_issuer internal
    order s3proxy first
    debug
}

website1.local, website2.local {
    s3proxy {
        bucket my-static-website-cache-bucket
        region eu-central-1
        index  index.html
        root   {host}
        #pass_thru
    }
    reverse_proxy localhost:8080 {
        header_up X-Forwarded-Host {host}
        header_up X-Forwarded-Port {port}
        header_up X-Forwarded-Proto {proto}
    }
}
```

And a custom key could look like this

```
    s3proxy {
        bucket my-static-website-cache-bucket
        region eu-central-1
        key  {host}/{path}/{sha1(query)} # not sure if there is a way to interpolate this somehow
    }
```

If you point me to the right places I could try to contribute here. I'm much into this use-case. I'm right now implementing the full-page-cache on the application side but I could imagine to add it pretty into caddy since caddy is the first hop in my stack.

**Comment by rayjlinden** [comment]
Ok, I added some initial support for a "pass_through" option.  I had to refactor the code a bit to make it clean to do.  However, I have not had much time to test this...

Check out the README for the instructions.

However, in your use case you can probably just do something like this:
```
errors pass_through
```

With respect to your other request - I'm not sure I understand it very well.  Caddy itself has some ways to rewrite URLs before they get to a directive.  I already take advantage of that with the `root` directive.  You can see some examples in the examples/Caddyfile.  However, I have never tried making a query string value part of the rewrite.  Maybe Caddy does this already with the rewrite or uri directive?  I don't know...

In any case, try the pass_through stuff and tell me how it works for you.  I'd suggest opening another issue for this query string stuff.

**Comment by christoph-kluge** [comment]
This is awesome. Thank you! I saw that you changed quite a lot. I will test this as soon as possible and will give you an feedback on my use-case.

Regarding the other issue/request I will file another issue (or better use-case) which will make it more clear. Sorry for this.

**Comment by christoph-kluge** [comment]
This works pretty nice! I just discovered one misleading issue with missing log-information.

When I was performing a request w/o path-info (literally `/`) then it was using the configured `root` + `index` but failed with error-permissions which are "not" displayed inside the log. I just realised it by seeing the next hop to the reverse proxy and started to dig.

## 1. Case: `GET /` with correct permission parameters

This works as expected.

```
2020/11/16 11:12:16.399 INFO    http.handlers.s3proxy   get from S3     {"bucket": "<my-bucket>", "key": "www.customer1.company.local/index.html"}
```

## 2. Case: `GET /` with incorrect permission parameters (in this case I would have expected the error message)

This works as expected BUT was missing the s3 error message. 

```
2020/11/16 11:15:42.855 INFO    http.handlers.s3proxy   get from S3     {"bucket": "<my-bucket>", "key": "www.customer1.company.local/index.html"}
2020/11/16 11:15:44.649 DEBUG   http.handlers.reverse_proxy     upstream roundtrip     <REDACTED>
```

## 3. Case: `GET /news` with incorrect permission parameters

This works as expected and gave me the proper error message.

```
2020/11/16 11:17:10.437 INFO    http.handlers.s3proxy   get from S3     {"bucket": "<my-bucket>", "key": "www.customer1.company.local/news"}
2020/11/16 11:17:10.595 ERROR   http.handlers.s3proxy   failed to get object    {"bucket": "<my-bucket>", "key": "www.customer1.company.local/news", "err": "AccessDenied: Access Denied\n\tstatus code: 403, request id: XXXXX, host id: XXXXXX"}
2020/11/16 11:17:16.084 DEBUG   http.handlers.reverse_proxy     upstream roundtrip      <REDACTED>
```

**Comment by rayjlinden** [comment]
Going to close this as I think it is fully implemented.  Any other issues should be a new bug.
