### ISSUE TITLE
Add support for accelerate endpoints

### ISSUE THREAD

**Issue by christoph-kluge** [lindenlab/caddy-s3-proxy#29]
S3 supports accelerated endpoints. These endpoints contain the bucket-name inside the endpoint itself. I have tried several configurations but was not able to set them up correctly. I received always a 404 status-code. 

I can imagine that this is due to the duplicate bucket-name inside the endpoint and inside the key. This was my example:

```
    s3proxy {
        endpoint    <bucket-name>.s3-accelerate.amazonaws.com
        bucket      <bucket-name>
        region      eu-central-1
        index       index.html
        root        {host}
        errors      pass_through
    }
```

Inside the php-aws-sdk this is solved by using a `use_accelerate_endpoint` boolean flag for the client. This tells the SDK to internally transform the endpoint and use the accelerated endpoint. I saw that the go-aws-sdk has the same option. It's just name a little bit differently: https://github.com/aws/aws-sdk-go/blob/0d8d5fad7f70e9fa8d374081d5c0f91b42f70bea/aws/config.go#L153

I think this is an easy pick for me which I could contribute to ;) Any suggestions how the option should be named/used here? I think the following example is pretty handy. What do you think @rayjlinden?

```
    s3proxy {
        use_accelerate
    }
```

**Comment by rayjlinden** [comment]
I think the thing breaking it is the line:
```
config.S3ForcePathStyle = aws.Bool(true)
```

This probably needs to be false for an accelerate endpoint to work.
I'd like to keep that as the default since it is need by localstack (and works fine for most AWS use cases).  But I suppose having an option to turn it off would be helpful.
