### ISSUE TITLE
Every other request 403'ing on the index

### ISSUE THREAD

**Issue by sweepyoface** [lindenlab/caddy-s3-proxy#42]
Caddyfile:

```
{
	order s3proxy last
	debug
}

example.com {
	s3proxy {
		bucket (redacted)
		region us-central1
		endpoint https://storage.googleapis.com
		index index.jpg
	}
}
```
Results in every other request throwing a 403 and this:
```
caddy    | {"level":"debug","ts":1610348010.7328117,"logger":"http.handlers.s3proxy","msg":"get from S3","bucket":"(redacted)","key":"/index.jpg"}
caddy    | {"level":"debug","ts":1610348010.7426867,"logger":"http.stdlib","msg":"http: superfluous response.WriteHeader call from github.com/caddyserver/caddy/v2/modules/caddyhttp.glob..func2 (caddyhttp.go:85)"}
```
I tested using S3 proper as well and got the same result. I'm totally lost here. Any ideas?

**Comment by rayjlinden** [comment]
Well, 403 would be saying it is permissions error.  I've never tried it with google's storage.  But I would assume it needs some kind of authentication?  You say you tried it against S3.  But a 403 in that case would mean that you have the wrong permissions.  Can you do it with awscli from the same serverr?

The superflous response.WriterHeader is saying someone is trying to write the response a second time.  I wonder if it has anything to do with the "order s3proxy last" directive.  I'm not sure I understand why the error is coming from the caddyhttp.glob..func2.

I'm not sure I have enough in this report to go on.

**Comment by sweepyoface** [comment]
Since it's every *other* request that gives me an error, it wouldn't make sense to be an authentication problem. It works fine exactly half of the time, and when it happens, nothing is different in the log (the same "get from S3 bucket" line). It's just like Caddy is giving me a 403 for no reason.

The s3proxy has to be explicitly ordered, so where do you suggest I put it?

**Comment by sweepyoface** [comment]
Okay, I have no clue what's going on. I'm getting completely different behaviour when testing with a command line tool vs Chrome.

**Comment by rayjlinden** [comment]
Well generally, I would put the proxy only on a specific route.  Within a
route ordering is explicit anyway.  (In which case ordering is not needed.)

Concerning your other problem I'm guessing you have multiple directives
going on and they are competing.  This is another reason to put specific
behavior behind specific routes.  At least for me that helps me ensure only
the directives I want applied are applied to a specific part of the site.

**Comment by sweepyoface** [comment]
I've solved this using `handle`. Thanks.
