### ISSUE TITLE
How can I use multiple profiles?

### ISSUE THREAD

**Issue by axel-verse** [lindenlab/caddy-s3-proxy#43]
For some reason I must support several accounts. So is there a way to configure s3proxy to use several profiles (for example, from .aws/credentials)?

Very thanks for your plugin, it is great!

**Comment by rayjlinden** [comment]
Not currently.  I've never used profiles so I guess the thought never
occurred to me...

If you know how to write go - a Pull Request would be great.  Otherwise,
I'll read up on using profiles tonight.  I can't imagine it would be too
hard to support.

**Comment by rayjlinden** [comment]
I just releases version 0.5.6 of s3-proxy.  It includes a new "profile" directive you can use to specify specific credentials out of a shared credentials file.

I was not able to test it much.  So please let me know how it works out for you,.

**Comment by axel-verse** [comment]
Thanks you very much, you are awesome )))

I will test it tonight

**Comment by axel-verse** [comment]
Tested and works like a charm ))) No errors encoutered, no unwanted behaviour faced. I am just delighted
