### ISSUE TITLE
Key is changed to include working-dir path?

### ISSUE THREAD

**Issue by Richard87** [lindenlab/caddy-s3-proxy#47]
I don't know how to explain it, but I have this request:
`/dashboard/task/scorm/59/cloud/e86d93a9-478e-4184-833d-93351f7823f4/settings.js?v=1618840488153`
that is rewritten to:
`/course/e86d93a9-478e-4184-833d-93351f7823f4_files/settings.js?v=1618840488153`
(found from Caddy's debug log)
But I get 404 from s3proxy where it gives me this key: 
`/var/www/public/course/e86d93a9-478e-4184-833d-93351f7823f4_files/settings.js`

```
{
    debug
    http_port 8000
}

:8000 {
    log
    root * /var/www/public

    php_fastcgi unix//var/run/php/php-fpm.sock

    encode zstd gzip
    file_server

    @staticFiles path (.css|.js|.woff2|.ttf)$
    header $staticFiles Cache-Control "public, max-age=604800"
    respond /health/caddy 200

    @s3 {
        path_regexp scorm_asset ^/dashboard/task/scorm/([0-9]+)/cloud/([0-9\-a-f]+)/(.*)$
    }
    route @s3 {
        rewrite @s3 /course/{http.regexp.scorm_asset.2}_files/{http.regexp.scorm_asset.3}
        s3proxy {
            bucket eportal_dev
            region auto
            endpoint https://storage.googleapis.com
            force_path_style
        }
    }
}
```

**Comment by Richard87** [comment]
Adding `root /` to s3proxy block solved the issue :) 

```
        s3proxy {
            root /
            bucket eportal_dev
            region auto
            endpoint https://storage.googleapis.com
            force_path_style
        }
```

**Comment by rayjlinden** [comment]
Glad you figured this out!

**Comment by Richard87** [comment]
Thanks! Btw, I had a problem I have been wrestling with for 4-5 days now, some external apps (SCORM course), downloading 3-400 files, that crashed the webserver (iknow, WIP to fix *that* bug :D) 

After trying out presigned urls to google storage, I figured out they didn't support CORS when authenticating URLs... Then I tried the same with MinIO, but the server still crashed trying to sign all the URLs...

Anyway, I tried s3proxy, and everything worked *perfectly, and fast!*...

Thank you!
